version: "3"  # Anda dapat menghapus baris ini jika ingin.

services:
  app:
  ports:
    - "9000:9000" 
    build:
      context: .  # Pastikan ada Dockerfile di direktori ini.
    image: isa_rental_mobil_website-master
    container_name: isa_rental_mobil_website-master
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/isa_rental_mobil_website-master
    volumes:
      - .:/var/www/isa_rental_mobil_website-master
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - isa_rental_mobil_website-master

  webserver:
    image: nginx:alpine
    container_name: nginxisa_rental_mobil_website-master
    restart: unless-stopped
    tty: true
    ports:
      - "2022:80"
    volumes:
      - .:/var/www/isa_rental_mobil_website-master
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Pastikan jalur ini benar
    networks:
      - isa_rental_mobil_website-master

  db:
    image: mysql:5.7
    container_name: dbisa_rental_mobil_website-master
    restart: always
    tty: true
    ports:
      - "20222:3306"
    volumes:
      - lbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ilhamalthaf
      MYSQL_DATABASE: isa
    networks:
      - isa_rental_mobil_website-master

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmaisa_rental_mobil_website-master
    links:
      - db
    restart: always
    ports:
      - "7000:80"
    networks:
      - isa_rental_mobil_website-master

networks:
  isa_rental_mobil_website-master:
    driver: bridge

volumes:
  lbdata:
